apiVersion: v1
kind: Service
metadata:
  name: nginx-v1
  namespace: default
  labels:
    app: nginx-v1
spec:
  ports:
  - port: 80
    protocol: TCP
    name: http
  selector:
    app: nginx-v1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-v1-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: nginx-v1
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx-v1
    spec:
      containers:
      - name: nginx-v1
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 200m
          requests:
            cpu: 100m
        volumeMounts:
        - name: workdir
          mountPath: /usr/share/nginx/html  # storage to file /usr/share/nginx/html/
      initContainers:
      - name: install
        image: busybox
        command:
        - wget
        - "-O"
        - "/work-dir/index.html"  # storage to file /usr/share/nginx/html/
        - https://raw.githubusercontent.com/asosluev/diplom/master/k8s/html/hello-world-v1/index.html
        volumeMounts:
        - name: workdir
          mountPath: "/work-dir"
      dnsPolicy: Default
      volumes:
      - name: workdir
        emptyDir: {}
---
# Add HPA
kind: HorizontalPodAutoscaler 
apiVersion: autoscaling/v1
metadata: 
  name: nginx-v1-deployment
spec: 
  maxReplicas: 10 
  minReplicas: 1 
  scaleTargetRef: 
    apiVersion: apps/v1 
    kind: Deployment 
    name: nginx-v1-deployment
  targetCPUUtilizationPercentage: 2
status:
  currentCPUUtilizationPercentage: 0
  currentReplicas: 1
  desiredReplicas: 1